本笔记本实现df数据到窗口数据的转换。

In [1]:
from constants import *

In [4]:
from data_load import *

In [5]:
data = load_data_from_h5('./well_log_daqing_standardized.h5', strategy= DefaultDataLoader())
data

,BHC,CAL,DEN,DEPT,GR,HAC,RMG,RMN,RMN-RMG,SP,WellName
0,1.354331,1.382265,0.021540,-1.575040,-0.076729,1.203110,2.260,2.265,-0.687548,1.389699,A1
1,1.331241,1.345440,0.073887,-1.574611,-0.067284,1.092743,2.241,2.281,-0.658715,1.389699,A1
2,1.314226,1.298230,0.178583,-1.574182,-0.068630,1.044477,2.405,2.474,-0.634824,1.378332,A1
3,1.325168,1.260461,0.073887,-1.573753,-0.076729,1.090462,2.598,2.640,-0.657067,1.358426,A1
4,1.338521,1.232135,0.178583,-1.573324,-0.094258,1.242187,2.533,2.538,-0.687548,1.338520,A1
...,...,...,...,...,...,...,...,...,...,...,...
38729,-0.231540,-0.852690,-1.580308,0.359415,-0.367605,-0.233752,6.191,8.237,0.993849,-1.949959,A6
38730,-0.282565,-0.881016,-1.287160,0.359844,-0.346479,-0.233752,5.867,8.042,1.100121,-1.953868,A6
38731,-0.332362,-0.895179,-1.077768,0.360273,-0.320068,-0.240638,6.723,9.164,1.319255,-1.959762,A6
38732,-0.373673,-0.859299,-0.931194,0.360702,-0.279134,-0.240638,7.263,9.530,1.175912,-1.953868,A6
38733,-0.496356,-0.798870,-0.920724,0.361131,-0.248756,-0.587599,6.874,8.828,0.918059,-1.949959,A6

In [6]:
# 设置输入特征和目标变量的列名
x_vars = ['DEPT', 'RMN-RMG', 'CAL', 'SP', 'GR', 'HAC', 'BHC', 'DEN']
x_vars_idx = [data.columns.get_loc(col) for col in x_vars]

In [12]:
from tsai.basics import *

# 设置滑动窗口的长度和滑动步长
window_len = TRAIN_LEN
data = data[x_vars]

# 调用apply_sliding_window函数接口
X,y  = apply_sliding_window(data, window_len, x_vars_idx)

# 输出结果
print("X shape:", X.shape)
print("X[0]:", X[0])
print("X[1]:", X[1])

X shape: (38526, 8, 200)
X[0]: [[-1.5750396  -1.57461064 -1.57418167 ... -1.49053337 -1.4901044
  -1.48967544]
 [-0.687548   -0.65871463 -0.63482412 ... -0.97423408 -0.6175241
  -0.51784302]
 [ 1.38226468  1.34544033  1.29822963 ...  0.92337667  0.94226095
   0.97625266]
 ...
 [ 1.20311014  1.09274285  1.04447734 ...  1.46978626  1.40310109
   1.33185405]
 [ 1.35433124  1.33124144  1.31422551 ...  1.42237223  1.38226649
   1.37255285]
 [ 0.02153951  0.07388748  0.17858342 ... -1.5593692  -1.5488996
  -1.52796042]]
X[1]: [[-1.57461064 -1.57418167 -1.5737527  ... -1.4901044  -1.48967544
  -1.48924647]
 [-0.65871463 -0.63482412 -0.65706701 ... -0.6175241  -0.51784302
  -0.64141461]
 [ 1.34544033  1.29822963  1.26046107 ...  0.94226095  0.97625266
   1.00552329]
 ...
 [ 1.09274285  1.04447734  1.09046191 ...  1.40310109  1.33185405
   1.15252065]
 [ 1.33124144  1.31422551  1.32516757 ...  1.38226649  1.37255285
   1.38106082]
 [ 0.07388748  0.17858342  0.07388748 ... -1.5488996  -1.52796042
  -1.42326448]]

存储起来作为SAITS的模型的数据输入。

In [13]:
import numpy as np

# 假设X是你的numpy.ndarray
# 保存数据到文件
np.save('data_input.npy', X)

In [14]:
import numpy as np

# 加载数据
X = np.load('data_input.npy')